name: money-app
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneybot_app
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/money_tracker.db
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./graphs:/app/graphs
      - ./reports:/app/reports
    working_dir: /app
    command: python main.py
